#!/bin/bash
# setup.sh — XMTP Skill Auto-Configuration
#
# Usage:
#   bash setup.sh --key 0xYourETHPrivateKey   # Direct setup
#   bash setup.sh                              # Interactive guidance
#
# Prerequisites:
#   - Node.js ≥ 20

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

echo "🔧 XMTP Skill Setup"
echo "===================="
echo ""

# ── Step 1: Check if already configured ──
if [ -f "$ENV_FILE" ]; then
  echo "⚠️  .env already exists: $ENV_FILE"
  echo "   To reconfigure, delete it first: rm $ENV_FILE"
  echo "   Or edit it manually."
  exit 0
fi

# ── Step 2: Get the private key ──
PRIVATE_KEY=""

# Source 1: --key argument
if [ "$1" = "--key" ] && [ -n "$2" ]; then
  PRIVATE_KEY="$2"
  echo "🔑 Private key received (prefix: ${PRIVATE_KEY:0:6}...)"
fi

# Source 2: ETH_PRIVATE_KEY environment variable
if [ -z "$PRIVATE_KEY" ] && [ -n "$ETH_PRIVATE_KEY" ]; then
  PRIVATE_KEY="$ETH_PRIVATE_KEY"
  echo "🔑 Read from ETH_PRIVATE_KEY env var"
fi

# Source 3: XMTP_WALLET_KEY environment variable
if [ -z "$PRIVATE_KEY" ] && [ -n "$XMTP_WALLET_KEY" ]; then
  PRIVATE_KEY="$XMTP_WALLET_KEY"
  echo "🔑 Read from XMTP_WALLET_KEY env var"
fi

# No key found — print help
if [ -z "$PRIVATE_KEY" ]; then
  echo "No private key provided. Three ways to configure:"
  echo ""
  echo "  1. Pass directly (recommended):"
  echo "     bash setup.sh --key 0xYourPrivateKey"
  echo ""
  echo "  2. Set environment variable:"
  echo "     ETH_PRIVATE_KEY=0x... bash setup.sh"
  echo ""
  echo "  3. Manual configuration:"
  echo "     cp .env.example .env"
  echo "     # then edit .env and fill in your private key"
  echo ""
  echo "  Don't have a key? Generate one:"
  echo "     node -e \"const w=require('crypto').randomBytes(32);console.log('0x'+w.toString('hex'))\""
  echo ""
  exit 1
fi

# ── Step 3: Validate key format ──
if [[ ! "$PRIVATE_KEY" =~ ^0x[0-9a-fA-F]{64}$ ]]; then
  echo "❌ Invalid private key format."
  echo "   Expected: 0x followed by 64 hex characters (66 chars total)"
  echo "   Got: ${PRIVATE_KEY:0:6}... (${#PRIVATE_KEY} chars)"
  exit 1
fi

# ── Step 4: Generate DB encryption key ──
DB_ENC_KEY="0x$(node -e "process.stdout.write(require('crypto').randomBytes(32).toString('hex'))")"
echo "🔐 Generated DB encryption key"

# ── Step 5: Write .env ──
cat > "$ENV_FILE" << EOF
# XMTP Agent Configuration
# Generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

XMTP_ENV=dev
XMTP_WALLET_KEY=$PRIVATE_KEY
XMTP_DB_ENCRYPTION_KEY=$DB_ENC_KEY
XMTP_DB_PATH=./data/xmtp-db
EOF

chmod 600 "$ENV_FILE"
echo "✅ .env created (permission: 600)"

# ── Step 6: Install dependencies ──
if [ ! -d "$SCRIPT_DIR/node_modules" ]; then
  echo ""
  echo "📦 Installing npm dependencies..."
  cd "$SCRIPT_DIR" && npm install --silent 2>/dev/null || npm install
  echo "✅ Dependencies installed"
fi

# ── Step 7: Create data directory ──
mkdir -p "$SCRIPT_DIR/data"

# ── Step 8: Verify ──
echo ""
echo "🧪 Verifying XMTP identity..."
cd "$SCRIPT_DIR"
RESULT=$(node send.mjs --info 2>/dev/null || echo "VERIFY_FAILED")

if echo "$RESULT" | grep -q '"address"'; then
  ADDR=$(echo "$RESULT" | node -e "let d='';process.stdin.on('data',c=>d+=c);process.stdin.on('end',()=>{try{console.log(JSON.parse(d).address)}catch(e){console.log('unknown')}})" 2>/dev/null || echo "unknown")
  echo ""
  echo "=========================================="
  echo "✅ XMTP identity created!"
  echo "🤖 Your address: $ADDR"
  echo "🌐 Network: dev"
  echo "=========================================="
  echo ""
  echo "Share this address with your communication partner."
  echo ""
  echo "  Send:  node send.mjs 0xPartnerAddress \"Hello!\""
  echo "  Check: node send.mjs --check 0xPartnerAddress"
  echo "  Info:  node send.mjs --info"
else
  echo "⚠️  Verification incomplete (may need network on first run)"
  echo "   Config saved. Test manually later:"
  echo "   cd $SCRIPT_DIR && node send.mjs --info"
fi

echo ""
echo "✅ Setup complete!"
