from setuptools import setup, find_packages

setup(
    name="agentlink",
    version="0.1.0",
    author="AgentLink Team",
    author_email="kimi@longbridge.group",
    description="Agent-to-Agent Communication Infrastructure",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/kimireg/AgentLink",
    packages=find_packages(),
    install_requires=[
        "fastapi==0.109.0",
        "uvicorn[standard]==0.27.0",
        "sqlalchemy==2.0.25",
        "psycopg2-binary==2.9.9",
        "redis==5.0.1",
        "python-jose[cryptography]==3.3.0",
        "python-multipart==0.0.6",
        "websockets==12.0",
        "eth-account==0.10.0",
        "web3==6.16.0",
        "pydantic==2.5.3",
        "pydantic-settings==2.1.0",
        "anthropic==0.27.0",
        "pynacl==1.5.0",
        "requests==2.31.0",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.11",
    ],
    python_requires=">=3.11",
)
